#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi
# Customize to your needs...
# source alias definitions
if [[ -s "${ZDOTDIR:-$HOME}/.alias.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.alias.zsh"
fi

if [[ -s "${ZDOTDIR:-$HOME}/bin/functions.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/bin/functions.sh"
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# added by travis gem
[ -f /home/jim/.travis/travis.sh ] && source /home/jim/.travis/travis.sh
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

